# Generated by Django 5.1.3 on 2024-12-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "admin_manager",
            "0002_user_address_user_date_join_alter_order_status_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="contact_name",
        ),
        migrations.AlterField(
            model_name="contact",
            name="lifecycle_stage",
            field=models.CharField(
                choices=[
                    ("SUBSCRIBER", "Subscriber"),
                    ("LEAD", "Lead"),
                    ("OPPORTUNITY", "Opportunity"),
                    ("EVANGELIST", "Evangelist"),
                ],
                max_length=50,
            ),
        ),
    ]
