# Generated by Django 5.1.3 on 2024-12-04 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_manager", "0003_remove_ticket_contact_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "campaign_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("campaign_name", models.CharField(max_length=255)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CLOSED", "Closed"),
                            ("IN_PROGRESS", "In progress"),
                            ("IN_PROGRESSED", "In progressed"),
                            ("PLANNED", "Planned"),
                        ],
                        default="PLANNED",
                        max_length=20,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaigns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
