# Generated by Django 5.1.3 on 2024-12-04 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_manager", "0004_campaign"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="staff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaigns",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="status",
            field=models.CharField(
                choices=[
                    ("PLANNED", "Planned"),
                    ("IN_PROGRESS", "In progress"),
                    ("IN_PROGRESSED", "In progressed"),
                    ("CLOSED", "Closed"),
                ],
                default="PLANNED",
                max_length=20,
            ),
        ),
    ]
