# Generated by Django 5.1.3 on 2024-12-04 02:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_manager", "0005_alter_campaign_staff_alter_campaign_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="campaign",
            old_name="campaign_name",
            new_name="name",
        ),
        migrations.AlterField(
            model_name="campaign",
            name="campaign_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
