# Generated by Django 5.1.3 on 2024-12-04 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_manager", "0006_rename_campaign_name_campaign_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailTrack",
            fields=[
                ("track_id", models.AutoField(primary_key=True, serialize=False)),
                ("is_send", models.BooleanField(default=False)),
                ("is_open", models.BooleanField(default=False)),
                ("is_click", models.BooleanField(default=False)),
                ("is_unsubscribe", models.BooleanField(default=False)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mail_tracks",
                        to="admin_manager.campaign",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mail_tracks",
                        to="admin_manager.contact",
                    ),
                ),
            ],
        ),
    ]
