# Generated by Django 5.1.3 on 2024-12-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_manager", "0007_mailtrack"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
