# Generated by Django 5.1.3 on 2024-12-15 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_manager", "0010_rename_subtotal_orderdetail_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="owner",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contacts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
    ]
