# Generated by Django 5.1.3 on 2024-12-18 01:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_manager", "0011_contact_owner_alter_contact_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("CONFIRMED", "Confirmed"),
                    ("IN_PROGRESS", "In-Progress"),
                    ("DELIVERED", "Delivered"),
                    ("RETURNED", "Returned"),
                ],
                max_length=50,
            ),
        ),
    ]
